// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {store} from '../models';
import {conflict} from '../models';

export function AddDevice(arg1:string,arg2:string):Promise<void>;

export function AddFolder(arg1:string,arg2:string):Promise<void>;

export function BackupNow():Promise<void>;

export function CancelBackup():Promise<void>;

export function Conflicts(arg1:string):Promise<Array<conflict.Conflict>>;

export function CopyText(arg1:string):Promise<void>;

export function Devices():Promise<main.DevicesView>;

export function DismissDevice(arg1:string):Promise<void>;

export function Folders():Promise<Array<main.FolderView>>;

export function InstallSyncthing():Promise<void>;

export function Log():Promise<Array<string>>;

export function ManifestUpdated():Promise<number>;

export function OpenBackupFolder():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenSyncthingGUI():Promise<void>;

export function Overview():Promise<main.Overview>;

export function PasteText():Promise<string>;

export function PickBackupFolder():Promise<string>;

export function PickFolder():Promise<string>;

export function RemoveDevice(arg1:string):Promise<void>;

export function RemoveFolder(arg1:string):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Restore(arg1:string,arg2:number):Promise<number>;

export function RestorePoints(arg1:string):Promise<Array<number>>;

export function SaveSettings(arg1:store.Settings):Promise<store.Settings>;

export function ScanGames(arg1:boolean):Promise<Array<main.GameView>>;

export function SetFolderBackup(arg1:string,arg2:boolean):Promise<void>;

export function StartSyncthing():Promise<void>;
