// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBackupOnly(arg1, arg2) {
  return window['go']['main']['App']['AddBackupOnly'](arg1, arg2);
}

export function AddDevice(arg1, arg2) {
  return window['go']['main']['App']['AddDevice'](arg1, arg2);
}

export function AddFolder(arg1, arg2) {
  return window['go']['main']['App']['AddFolder'](arg1, arg2);
}

export function Available() {
  return window['go']['main']['App']['Available']();
}

export function BackupNow() {
  return window['go']['main']['App']['BackupNow']();
}

export function CancelBackup() {
  return window['go']['main']['App']['CancelBackup']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function Conflicts(arg1) {
  return window['go']['main']['App']['Conflicts'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function Devices() {
  return window['go']['main']['App']['Devices']();
}

export function DismissDevice(arg1) {
  return window['go']['main']['App']['DismissDevice'](arg1);
}

export function Folders() {
  return window['go']['main']['App']['Folders']();
}

export function InstallSyncthing() {
  return window['go']['main']['App']['InstallSyncthing']();
}

export function Log() {
  return window['go']['main']['App']['Log']();
}

export function ManifestUpdated() {
  return window['go']['main']['App']['ManifestUpdated']();
}

export function OpenBackupFolder() {
  return window['go']['main']['App']['OpenBackupFolder']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenSyncthingGUI() {
  return window['go']['main']['App']['OpenSyncthingGUI']();
}

export function OpenUpdate() {
  return window['go']['main']['App']['OpenUpdate']();
}

export function Overview() {
  return window['go']['main']['App']['Overview']();
}

export function PasteText() {
  return window['go']['main']['App']['PasteText']();
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function PickBackupFolder() {
  return window['go']['main']['App']['PickBackupFolder']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RemoveDevice(arg1) {
  return window['go']['main']['App']['RemoveDevice'](arg1);
}

export function RemoveFolder(arg1, arg2) {
  return window['go']['main']['App']['RemoveFolder'](arg1, arg2);
}

export function RemoveUninstalled() {
  return window['go']['main']['App']['RemoveUninstalled']();
}

export function ResolveConflict(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2, arg3);
}

export function Restore(arg1, arg2) {
  return window['go']['main']['App']['Restore'](arg1, arg2);
}

export function RestorePoints(arg1) {
  return window['go']['main']['App']['RestorePoints'](arg1);
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanGames(arg1) {
  return window['go']['main']['App']['ScanGames'](arg1);
}

export function SetFolderBackup(arg1, arg2) {
  return window['go']['main']['App']['SetFolderBackup'](arg1, arg2);
}

export function SetFolderSync(arg1, arg2) {
  return window['go']['main']['App']['SetFolderSync'](arg1, arg2);
}

export function StartSyncthing() {
  return window['go']['main']['App']['StartSyncthing']();
}

export function SyncAvailable(arg1) {
  return window['go']['main']['App']['SyncAvailable'](arg1);
}

export function UndoAll(arg1) {
  return window['go']['main']['App']['UndoAll'](arg1);
}
