// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Accounts() {
  return window['go']['main']['App']['Accounts']();
}

export function AddBackupOnly(arg1, arg2) {
  return window['go']['main']['App']['AddBackupOnly'](arg1, arg2);
}

export function AddBackupOnlyMany(arg1) {
  return window['go']['main']['App']['AddBackupOnlyMany'](arg1);
}

export function AddDevice(arg1, arg2) {
  return window['go']['main']['App']['AddDevice'](arg1, arg2);
}

export function AddFolder(arg1, arg2) {
  return window['go']['main']['App']['AddFolder'](arg1, arg2);
}

export function AddModFolder(arg1) {
  return window['go']['main']['App']['AddModFolder'](arg1);
}

export function AdoptBackup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AdoptBackup'](arg1, arg2, arg3, arg4);
}

export function ApplyModUpdate(arg1, arg2) {
  return window['go']['main']['App']['ApplyModUpdate'](arg1, arg2);
}

export function Available() {
  return window['go']['main']['App']['Available']();
}

export function BackupNow() {
  return window['go']['main']['App']['BackupNow']();
}

export function CancelBackup() {
  return window['go']['main']['App']['CancelBackup']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConflictOwners(arg1) {
  return window['go']['main']['App']['ConflictOwners'](arg1);
}

export function Conflicts(arg1) {
  return window['go']['main']['App']['Conflicts'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function CreateAccount(arg1, arg2) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteOtherBackup(arg1, arg2) {
  return window['go']['main']['App']['DeleteOtherBackup'](arg1, arg2);
}

export function DeleteSaves(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSaves'](arg1, arg2, arg3);
}

export function Devices() {
  return window['go']['main']['App']['Devices']();
}

export function DismissDevice(arg1) {
  return window['go']['main']['App']['DismissDevice'](arg1);
}

export function EditAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditAccount'](arg1, arg2, arg3);
}

export function Folders() {
  return window['go']['main']['App']['Folders']();
}

export function GetNewer(arg1) {
  return window['go']['main']['App']['GetNewer'](arg1);
}

export function HandOverMods(arg1) {
  return window['go']['main']['App']['HandOverMods'](arg1);
}

export function InstallSyncthing() {
  return window['go']['main']['App']['InstallSyncthing']();
}

export function LeaveToSteamCloud() {
  return window['go']['main']['App']['LeaveToSteamCloud']();
}

export function Log() {
  return window['go']['main']['App']['Log']();
}

export function MakeModSource(arg1) {
  return window['go']['main']['App']['MakeModSource'](arg1);
}

export function ManifestUpdated() {
  return window['go']['main']['App']['ManifestUpdated']();
}

export function MergeGame(arg1, arg2) {
  return window['go']['main']['App']['MergeGame'](arg1, arg2);
}

export function ModAudit(arg1) {
  return window['go']['main']['App']['ModAudit'](arg1);
}

export function ModSnapshots(arg1) {
  return window['go']['main']['App']['ModSnapshots'](arg1);
}

export function ModUpdatePreview(arg1) {
  return window['go']['main']['App']['ModUpdatePreview'](arg1);
}

export function OpenBackupFolder() {
  return window['go']['main']['App']['OpenBackupFolder']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenSyncthingGUI() {
  return window['go']['main']['App']['OpenSyncthingGUI']();
}

export function OpenUpdate() {
  return window['go']['main']['App']['OpenUpdate']();
}

export function OtherBackups(arg1) {
  return window['go']['main']['App']['OtherBackups'](arg1);
}

export function Overview() {
  return window['go']['main']['App']['Overview']();
}

export function PasteText() {
  return window['go']['main']['App']['PasteText']();
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function PickBackupFolder() {
  return window['go']['main']['App']['PickBackupFolder']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function ReleaseModHold(arg1) {
  return window['go']['main']['App']['ReleaseModHold'](arg1);
}

export function RemoveDevice(arg1) {
  return window['go']['main']['App']['RemoveDevice'](arg1);
}

export function RemoveFolder(arg1, arg2) {
  return window['go']['main']['App']['RemoveFolder'](arg1, arg2);
}

export function RemoveUninstalled() {
  return window['go']['main']['App']['RemoveUninstalled']();
}

export function ResolveConflict(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2, arg3);
}

export function ResolveConflicts(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflicts'](arg1, arg2);
}

export function Restore(arg1, arg2) {
  return window['go']['main']['App']['Restore'](arg1, arg2);
}

export function RestorePoints(arg1) {
  return window['go']['main']['App']['RestorePoints'](arg1);
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function RetryAccountChange() {
  return window['go']['main']['App']['RetryAccountChange']();
}

export function RollbackMods(arg1, arg2) {
  return window['go']['main']['App']['RollbackMods'](arg1, arg2);
}

export function RunModAudit(arg1) {
  return window['go']['main']['App']['RunModAudit'](arg1);
}

export function SaveOwners(arg1) {
  return window['go']['main']['App']['SaveOwners'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanGames(arg1) {
  return window['go']['main']['App']['ScanGames'](arg1);
}

export function SetAccountsEnabled(arg1) {
  return window['go']['main']['App']['SetAccountsEnabled'](arg1);
}

export function SetExclusions(arg1, arg2) {
  return window['go']['main']['App']['SetExclusions'](arg1, arg2);
}

export function SetFolderBackup(arg1, arg2) {
  return window['go']['main']['App']['SetFolderBackup'](arg1, arg2);
}

export function SetFolderSync(arg1, arg2) {
  return window['go']['main']['App']['SetFolderSync'](arg1, arg2);
}

export function SignInGoogle() {
  return window['go']['main']['App']['SignInGoogle']();
}

export function SignOutGoogle() {
  return window['go']['main']['App']['SignOutGoogle']();
}

export function SplitGame(arg1, arg2) {
  return window['go']['main']['App']['SplitGame'](arg1, arg2);
}

export function StartSyncthing() {
  return window['go']['main']['App']['StartSyncthing']();
}

export function StopSyncingCopies() {
  return window['go']['main']['App']['StopSyncingCopies']();
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function SyncAvailable(arg1) {
  return window['go']['main']['App']['SyncAvailable'](arg1);
}

export function UndoAll(arg1) {
  return window['go']['main']['App']['UndoAll'](arg1);
}
