// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {conflict} from '../models';
import {accounts} from '../models';
import {mods} from '../models';
import {backup} from '../models';
import {store} from '../models';

export function Accounts():Promise<main.AccountsView>;

export function AddBackupOnly(arg1:string,arg2:string):Promise<void>;

export function AddBackupOnlyMany(arg1:Array<main.NewFolder>):Promise<main.BulkResult>;

export function AddDevice(arg1:string,arg2:string):Promise<void>;

export function AddFolder(arg1:string,arg2:string):Promise<void>;

export function AddModFolder(arg1:string):Promise<void>;

export function AdoptBackup(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<number>;

export function ApplyModUpdate(arg1:string,arg2:main.ApplyConfirm):Promise<void>;

export function Available():Promise<Array<main.AvailableView>>;

export function BackupNow():Promise<void>;

export function CancelBackup():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ConflictOwners(arg1:string):Promise<Array<main.ConflictOwner>>;

export function Conflicts(arg1:string):Promise<Array<conflict.Conflict>>;

export function CopyText(arg1:string):Promise<void>;

export function CreateAccount(arg1:string,arg2:string):Promise<accounts.Account>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteOtherBackup(arg1:string,arg2:string):Promise<void>;

export function DeleteSaves(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function Devices():Promise<main.DevicesView>;

export function DismissDevice(arg1:string):Promise<void>;

export function EditAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Folders():Promise<Array<main.FolderView>>;

export function GetNewer(arg1:string):Promise<number>;

export function HandOverMods(arg1:string):Promise<void>;

export function InstallSyncthing():Promise<void>;

export function LeaveToSteamCloud():Promise<number>;

export function Log():Promise<Array<string>>;

export function MakeModSource(arg1:string):Promise<void>;

export function ManifestUpdated():Promise<number>;

export function MergeGame(arg1:string,arg2:string):Promise<void>;

export function ModAudit(arg1:string):Promise<Array<mods.AuditEntry>>;

export function ModSnapshots(arg1:string):Promise<Array<main.SnapshotView>>;

export function ModUpdatePreview(arg1:string):Promise<main.ModPreview>;

export function OpenBackupFolder():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenSyncthingGUI():Promise<void>;

export function OpenUpdate():Promise<void>;

export function OtherBackups(arg1:boolean):Promise<Array<backup.Orphan>>;

export function Overview():Promise<main.Overview>;

export function PasteText():Promise<string>;

export function Pause(arg1:number):Promise<void>;

export function PickBackupFolder():Promise<string>;

export function PickFolder():Promise<string>;

export function ReleaseModHold(arg1:string):Promise<void>;

export function RemoveDevice(arg1:string):Promise<void>;

export function RemoveFolder(arg1:string,arg2:boolean):Promise<void>;

export function RemoveUninstalled():Promise<number>;

export function ResolveConflict(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ResolveConflicts(arg1:string,arg2:string):Promise<number>;

export function Restore(arg1:string,arg2:number):Promise<number>;

export function RestorePoints(arg1:string):Promise<Array<number>>;

export function Resume():Promise<void>;

export function RetryAccountChange():Promise<void>;

export function RollbackMods(arg1:string,arg2:string):Promise<void>;

export function RunModAudit(arg1:string):Promise<mods.AuditEntry>;

export function SaveOwners(arg1:string):Promise<Array<main.SaveFile>>;

export function SaveSettings(arg1:store.Settings):Promise<store.Settings>;

export function ScanGames(arg1:boolean):Promise<Array<main.GameView>>;

export function SetAccountsEnabled(arg1:boolean):Promise<void>;

export function SetExclusions(arg1:string,arg2:Array<string>):Promise<void>;

export function SetFolderBackup(arg1:string,arg2:boolean):Promise<void>;

export function SetFolderSync(arg1:string,arg2:boolean):Promise<void>;

export function SignInGoogle():Promise<string>;

export function SignOutGoogle():Promise<void>;

export function SplitGame(arg1:string,arg2:Record<string, string>):Promise<void>;

export function StartSyncthing():Promise<void>;

export function StopSyncingCopies():Promise<number>;

export function SwitchAccount(arg1:string):Promise<void>;

export function SyncAvailable(arg1:string):Promise<void>;

export function UndoAll(arg1:main.UndoOptions):Promise<main.UndoReport>;
